### ISSUE TITLE
Extension doesn't work, but no errors

### ISSUE THREAD

**Issue by Alpvax** [Tyriar/vscode-shell-launcher#9] opened 2017-10-13 15:17 UTC
Any terminal windows I open through this extension generate a new terminal window, but none of them have a prompt.
On Windows 10 x64, tried with bash subsystem, powershell and cmd, all have the same result of a blank terminal.

**Comment by Tiberriver256** [comment] 2017-10-18 02:26
Same thing for me. Any suggestions?

**Comment by Alpvax** [comment] 2017-10-18 09:23
No dice. Already on the 64 bit version.
![image](https://user-images.githubusercontent.com/1474110/31710902-4db6881a-b3ee-11e7-8776-c2673d0d63be.png)

**Comment by sipsorcery** [comment] 2017-10-19 05:32
Same problem.

**Comment by Mimetis** [comment] 2017-10-19 16:02
exact same problem here :)

**Comment by Tyriar** [comment] 2017-10-21 00:25
I think everyone was experiencing an issue in VS Code, not the extension. I'll close this off as a duplicate of https://github.com/Microsoft/vscode/issues/34554, please let me know if you're still seeing this after updating to 1.17.2.

**Comment by Mimetis** [comment] 2017-10-23 06:14
Hey @Tyriar, the issue is still active. I'm on the 1.17.2, and still can't launch any terminal within Shell Launcher

**Comment by Tyriar** [comment] 2017-10-28 08:35
@Mimetis ah I can reproduce, the paths on Windows should point to System32 since the 64-bit version was released.

**Comment by Tyriar** [comment] 2017-10-28 08:43
Fixed in https://github.com/Tyriar/vscode-shell-launcher/commit/6e9593821ec7393c056b18a498ab20d08dbc6b05 and published 0.1.4, thanks for pinging me again 😃

**Closed by Tyriar** 2017-10-28 08:43 UTC
Labels: bug
