### ISSUE TITLE
Launcher dropdown not displaying // help

### ISSUE THREAD

**Issue by factormrp** [Tyriar/vscode-shell-launcher#53] opened 2020-04-01 19:56 UTC
I followed basic setup and chose the keybind: "CTRL+ALT+` "

This has the effect of automatically creating a new Git bash terminal without allowing me to choose from the dropdown, which itself is not displayed.

When I attempted to switch the keybind to: "CTRL+ALT+T" I found that nothing occurred, despite VS Code registering the bind as a previously executed command when i open the command palette.

Below, I've attached photos of my settings.

![Screenshot (42)](https://user-images.githubusercontent.com/63017900/78180721-07602500-7418-11ea-85ae-2346294819d1.png)
![Screenshot (43)](https://user-images.githubusercontent.com/63017900/78180723-07f8bb80-7418-11ea-9111-69535a048f02.png)

Please help, as this extension seems awesome.

**Comment by Tyriar** [comment] 2020-04-05 04:12
Does CTRL+ALT+T work when assigned to other keybindings? Seems like this is likely a vscode problem not with the extension.

**Comment by factormrp** [comment] 2020-04-06 22:00
Hey! So i checked it out again and you're right that it was a simple bug regarding the CTRL+ALT+T bind. The shellLauncher command was executed. Yet the execution was not a dropdown. It simply launched a new GitBash terminal. It did not display a dropdown or in any way allow me to choose what kind of terminal to create.

is there any set up I might be missing? My VS Code is up to date and the extension is up to date (0.4.1)

thanks again

**Comment by Tyriar** [comment] 2020-04-06 22:41
I think the extension will not do the dropdown anymore if there is only a single option? Is that what's happening?

**Comment by factormrp** [comment] 2020-04-06 22:53
I was under the assumption that I had more than one option present:

![image](https://user-images.githubusercontent.com/63017900/78612682-cbb1ca80-781e-11ea-8d3c-5e6166848a53.png)

**Comment by Tyriar** [comment] 2020-04-06 23:25
Oh I think the problem is it says <sysnative> so there is only 1 valid one. Try `C:\\Windows\System32\\...` or `C:\\Windows\\Sysnative\\...`

**Closed by Tyriar** 2020-04-06 23:25 UTC
Labels: needs more info
